version: "3"

services:
  mysql:
    container_name: ddd_forum_mysql
    command: --default-authentication-plugin=mysql_native_password
    image: mysql:latest
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=rootpwd
      - MYSQL_DATABASE=ddd_forum_dev
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=pass

  adminer:
    image: adminer
    depends_on:
      - mysql
    ports:
      - 8080:8080

  redis:
    container_name: ddd_forum_redis
    image: redis:latest
    ports:
      - 6379:6379
